from django.contrib import admin
from sub_part.models import *

# Register your models here.
admin.site.register(StudentAdmission)
admin.site.register(OnlineExam)
admin.site.register(AddStaff)
admin.site.register(Purpose)
admin.site.register(ComplainType)
admin.site.register(Source)
admin.site.register(Reference)
admin.site.register(Section)
admin.site.register(Class)
admin.site.register(StudentCategory)
admin.site.register(StudentHouse)
admin.site.register(DisableReason)
admin.site.register(Route)
admin.site.register(Hostel)
admin.site.register(FeesGroup)
admin.site.register(FeesType)
admin.site.register(Incomehead)
admin.site.register(ExpenseHead)
admin.site.register(Role)
admin.site.register(AddLeaveType)
admin.site.register(Department)
admin.site.register(Designation)
admin.site.register(AddItem)
admin.site.register(ItemCategory)
admin.site.register(ItemStore)
admin.site.register(ItemSupplier)
admin.site.register(AdmissionEnquiry)
admin.site.register(VisitorBook)
admin.site.register(PhoneCallLog)
admin.site.register(PostalDispatch)
admin.site.register(PostalReceive)
admin.site.register(Complain)
admin.site.register(AddIncome)
admin.site.register(FeesMaster)
admin.site.register(AddExpense)
admin.site.register(FeesTypeDiscount)
admin.site.register(Addleave)
admin.site.register(examGroup)
admin.site.register(AdmitCard)
admin.site.register(DesignMarkSheet)
admin.site.register(AddGrade)
admin.site.register(QuestionBank)
admin.site.register(Lesson)
admin.site.register(topic)
admin.site.register(AssignClassTeacher)
admin.site.register(Subjects)
admin.site.register(SubjectGroup)
admin.site.register(ApproveLeave)
admin.site.register(ApplyLeave)
admin.site.register(noticeBoard)
admin.site.register(UploadContent)
admin.site.register(AddHomeWork)
admin.site.register(AddBook)
admin.site.register(IssueBook)
admin.site.register(LibrayMember)
admin.site.register(IssueItem)
admin.site.register(ItemStock)
admin.site.register(Vehicle)
admin.site.register(AssignVehicle)
admin.site.register(HostelRoom)
admin.site.register(RoomType)
admin.site.register(StudentCertificate)
admin.site.register(StudentId)
admin.site.register(Event)
admin.site.register(MediaManager)
admin.site.register(Menu)
admin.site.register(AlumniEvent)
admin.site.register(Session)
admin.site.register(Managealumini)
admin.site.register(StudentAttendance)
admin.site.register(PayrollSummary)
admin.site.register(User)
admin.site.register(AvailableLeave)
admin.site.register(LoginCredentials)
admin.site.register(TeacherRating)
admin.site.register(Infrastructure)
admin.site.register(SchoolHeads)
admin.site.register(FeesAssign)
admin.site.register(BasicWebPageDetails)
admin.site.register(Studentprofileupdate)
admin.site.register(PrintHeaderFooter)
admin.site.register(Modules)
admin.site.register(OnlineClass)
admin.site.register(StaffMeeting)
admin.site.register(ParentMeeting)
admin.site.register(LessonPlan)
admin.site.register(TimeTable)
admin.site.register(School)
admin.site.register(GradingScale)
admin.site.register(GeneralSetting)


class SchoolYearAdmin(admin.ModelAdmin):
    list_display = ("year",)
    search_fields = ("year",)


admin.site.register(SchoolYear, SchoolYearAdmin)
admin.site.register(AddExam)
admin.site.register(Term)
admin.site.register(AssetType)
admin.site.register(ChargeType)
admin.site.register(GLLine)
admin.site.register(TransactionCode)
admin.site.register(Account)
admin.site.register(AccountType)
admin.site.register(AccountEntry)
admin.site.register(TransactionType)
admin.site.register(PaymentRecord)
