# Generated by Django 4.2.7 on 2023-12-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_key_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=500, null=True)),
                ('mpesa_passkey', models.CharField(blank=True, max_length=500, null=True)),
                ('mpesa_consumer_key', models.CharField(blank=True, max_length=500, null=True)),
                ('mpesa_consumer_secret', models.CharField(blank=True, max_length=500, null=True)),
                ('seleted_payment', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
