# Generated by Django 4.2.7 on 2023-12-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_alter_session_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestypediscount',
            name='DiscountType',
        ),
        migrations.AddField(
            model_name='feestypediscount',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('Discount Percentage', 'Discount Percentage'), ('Discount Amount', 'Discount Amount')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feestypediscount',
            name='percentage_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feestypediscount',
            name='total_fees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='total_fees1', to='sub_part.feesmaster'),
        ),
        migrations.AlterField(
            model_name='feesmaster',
            name='amount',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feesmaster',
            name='fine_type',
            field=models.CharField(blank=True, choices=[('Select', 'Select'), ('Percentage', 'Percentage'), ('Fine Amount', 'Fine Amount')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feestypediscount',
            name='percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
