# Generated by Django 4.2.7 on 2023-12-21 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_remove_feestypediscount_discounttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestypediscount',
            name='fees_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_groups', to='sub_part.feesgroup'),
        ),
    ]
