# Generated by Django 4.2.7 on 2023-12-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_feestypediscount_fees_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestypediscount',
            name='fees_group',
        ),
    ]
