# Generated by Django 4.2.7 on 2024-01-09 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_studentadmission_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.account'),
        ),
    ]
