# Generated by Django 4.2.7 on 2024-01-10 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sub_part', '0008_studentadmission_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountentry',
            name='group_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trustee_belongs_group_name', to='auth.group'),
        ),
    ]
