# Generated by Django 4.2.7 on 2024-01-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sub_part', '0009_accountentry_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='account_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trustee_acc_number', to='sub_part.account'),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trustee_belongs_group_name', to='auth.group'),
        ),
    ]
