# Generated by Django 4.2.7 on 2024-01-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_alter_accountentry_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountentry',
            name='group_name',
        ),
    ]
