# Generated by Django 4.2.7 on 2024-01-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0011_remove_accountentry_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.account'),
        ),
    ]
