# Generated by Django 4.2.7 on 2024-01-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0014_addincome_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeTotlAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
