# Generated by Django 4.2.7 on 2024-01-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0018_alter_accountentry_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountentry',
            name='account_number',
        ),
        migrations.AddField(
            model_name='accountentry',
            name='school_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_account_entries', to='sub_part.account'),
        ),
        migrations.AddField(
            model_name='accountentry',
            name='student_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_account_entries', to='sub_part.account'),
        ),
    ]
