# Generated by Django 4.2.7 on 2024-01-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0019_remove_accountentry_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
