# Generated by Django 4.2.7 on 2024-01-23 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0021_addstaff_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addincome',
            name='user',
        ),
        migrations.AddField(
            model_name='accountentry',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.transactiontype'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='is_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='is_income',
            field=models.BooleanField(default=False),
        ),
    ]
